### PR TITLE
Bootstrap tagsinput keyup fix

### PR DESCRIPTION
**Pull request by shadowshades**
Line 178 :
$(this).css(width, 'auto')
to
$(this).css('width', 'auto')

### CODE REVIEW

**Comment by rahularyan** [comment]
Tags input has been updated and now its better then before, check latest commit.

**Comment by shadowshades** [comment]
Hello Rahul,
do you still work on it ? I have a little bug, when I hit enter, the form is submitted instead of adding the tag.
Also, I need to do some accessibility adjustements inside tags input for blind people using screen reader. 
If you dont work on it right now, I could work on it and propose you a new pull request.
Thank you,
Shad
Date: Tue, 15 Sep 2015 18:21:04 -0700

**Comment by rahularyan** [comment]
Look like a cache.

**Comment by shadowshades** [comment]
What do you mean ?

**Comment by rahularyan** [comment]
I think its browser cache. Try hard refresh of browser.

**Comment by shadowshades** [comment]
I've already tried, but it was not fixing the bug. I found I way to fix it inside the script tags_js.
Could I work on it and propose you a new Pull Request ? Thanks!

**Comment by rahularyan** [comment]
@shadowshades Yes this look like a bug for some browsers. I will check this.

**Comment by shadowshades** [comment]
Hello Rahul,
I've done a pull request for "tags-for-anspress" with a lot of improvements.
Tell me what do you think about it and if you can merge it with your master branch ;)
Thank you!

**Pull request closed without merging**
