### PR TITLE
Fix french translation

### PR DESCRIPTION
**Pull request by sebastienwarin**

### CODE REVIEW

**Comment by rahularyan** [comment]
Hello @sebastienwarin,
Will you please exclude .mo file?

**Comment by rahularyan** [comment]
Thanks I will check.

**Comment by sebastienwarin** [comment]
Hi,
I can't update my anspress to 4.0.5 because the french translation is not up to date ! Any new about my PR ?
Thank's

**Comment by rahularyan** [comment]
Hello @sebastienwarin,
Sorry for not merging your PR. In upcoming version I am reoving all .POs and .MOs from our plugin. As WordPress have better translation system so we will relay on it. You can visit and suggest translations:
https://translate.wordpress.org/projects/wp-plugins/anspress-question-answer

But language folder will be there in AnsPress so that you can override language.

Cheers.

**Comment by Pierre-Lannoy** [comment]
Hello all!

I’ve translated AnsPress plugin in french for the following locales: French (France), French (Belgium) and French (Canada) and I’m now translation editor for these locales on WP.org…

If you go to your WP admin in **Dashboard ► Updates ► Translations**, you will be able to update to the latest translation.

Many thanks, Rahul, for your great plugin!

**Comment by rahularyan** [comment]
Hello @Pierre-Lannoy,
Thanks a lot for your contributions.

**Pull request closed without merging**
