### PR TITLE
Changed hook and function name

### PR DESCRIPTION
**Pull request by rpf5573**
Check please!

### CODE REVIEW

**Comment by rpf5573** [comment]
I think f390469 is not bad. because Tags.php also do like that.
Could you accept f390469 only? ( Umm, I don't know this is possible in Git )

Check please!

**Comment by rahularyan** [comment]
> I think f390469 is not bad. because Tags.php also do like that.
Okay I have to check.
> Could you accept f390469 only? ( Umm, I don't know this is possible in Git )
yes possible. you can download the diff file by simply adding `.diff` to the end of commit url. like:
`https://github.com/anspress/anspress/commit/f390469d775d459b806e3739b638d79247b0a038.diff`

**Comment by rpf5573** [comment]
Sorry, I can't understand your answer.
I just wanted you to merge f390469 and 7c35c5b except b2176ec if they are OK to this project.
Or, Is it more good to make **re-create pull request** in this case ?

Check please!

**Comment by geetikaaryan** [comment]
No, not required. I will do it. Thanks
________________________________

**Comment by rahularyan** [comment]
Thank you. I have tested your PR, looks good. It will be merged in upcoming version.

**Comment by rahularyan** [comment]
Hello @rpf5573,
It seems some issue in your last commit. Let's discuss it on slack. Please send me your email to support@anspress.io
Thanks

**Pull request closed without merging**
